import { FC } from 'react'
import { Container, Typography } from '@mui/material'
import Head from 'next/head'

import Counter from '@Components/Counter/Counter'
import Search from '@Components/Search/Search'

const Home: FC = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <Container maxWidth="xl">
        <Typography variant="h1">Welcome to Daikozi Boilerplate 👋</Typography>
        <Counter />
        <Search />
      </Container>
    </main>
  </>
)

export default Home
